name       : acpid2
version    : 2.0.33
release    : 5
source     :
    - https://downloads.sourceforge.net/project/acpid2/acpid-2.0.33.tar.xz : 0856f71b3eb34a1b663d0a8e6363dfcbc519e63d847330498898658e2972dbe8
license    : GPL-2.0-or-later
component  : system.utils
summary    : acpid with netlink and input layer support
description: |
    acpid with netlink and input layer support
setup      : |
    %patch -p1 < $pkgfiles/0001-Move-contents-out-of-etc.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/anything $installdir/usr/share/acpi/events/anything
    install -Dm00744 $pkgfiles/handler.sh $installdir/usr/share/acpi/handler.sh
    install -Dm00644 $pkgfiles/acpid.service $installdir/%libdir%/systemd/system/acpid.service
    # Clean up a bunch of unneeded stuff
    rm -rf $installdir/usr/share/doc/
