name       : acpid2
version    : 2.0.31
release    : 1
source     :
    - https://downloads.sourceforge.net/project/acpid2/acpid-2.0.31.tar.xz : fc9dc669ed85d9a1739aa76915e0667c6697c5431160f8dfb253046c6a072cc3
license    : GPL-2.0-or-later
component  : system.utils
summary    : acpid with netlink and input layer support
description: |
    acpid with netlink and input layer support
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/anything $installdir/etc/acpi/events/anything
    install -Dm00744 $pkgfiles/handler.sh $installdir/etc/acpi/handler.sh
    install -Dm00644 $pkgfiles/acpid.service $installdir/%libdir%/systemd/system/acpid.service
    # Clean up a bunch of unneeded stuff
    rm $installdir/usr/share/doc/acpid/{COPYING,Changelog,TESTPLAN,TODO}
