name       : acpid2
version    : 2.0.32
release    : 4
source     :
    - https://downloads.sourceforge.net/project/acpid2/acpid-2.0.32.tar.xz : f2d2d30b3edc3234bd82f6f7186699a6aa3c85c8d20bc4e30e9b3c68a1ed157e
license    : GPL-2.0-or-later
component  : system.utils
summary    : acpid with netlink and input layer support
description: |
    acpid with netlink and input layer support
setup      : |
    %patch -p1 < $pkgfiles/0001-Move-contents-out-of-etc.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/anything $installdir/usr/share/acpi/events/anything
    install -Dm00744 $pkgfiles/handler.sh $installdir/usr/share/acpi/handler.sh
    install -Dm00644 $pkgfiles/acpid.service $installdir/%libdir%/systemd/system/acpid.service
    # Clean up a bunch of unneeded stuff
    rm -rf $installdir/usr/share/doc/
